FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the module's JAR file to the container
COPY rest/target/rest-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]