version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rest:
    build:
      context: .
      dockerfile: docker/Dockerfile.rest
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - kafka

  calculator:
    build:
      context: .
      dockerfile: docker/Dockerfile.calculator
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - kafka

networks:
  app-network:
    driver: bridge
